title: The Boring Blog
description: >- # this means to ignore newlines until "baseurl:"
  Commenting, venting, and ranting. Usually about entrepreneurship, tech, and self-reflection.
email: kasperi.keski.loppi@gmail.com
github_username:  cappe

# Build settings
host: 0.0.0.0
permalink: /blog/:title:output_ext
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
