version: '3.7'

services:
  jekyll:
    build:
      context: .
    command: bundle exec jekyll serve
    ports:
      - "4000:4000"
    volumes:
      - ./:/srv/jekyll
    tty: true
    stdin_open: true
